### PR TITLE
Patch volumeClaimTemplates

### PR DESCRIPTION
**Pull request by clyang82**
fixes: https://github.com/observatorium/deployments/issues/313

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
Do not have permission to rerun the failed circleci test.

**Comment by brancz** [comment]
I think we should only do this in the operator jsonnet.

**Comment by clyang82** [comment]
@brancz Thanks for response. Do you mean that we should do this in https://github.com/observatorium/deployments/blob/master/operator/jsonnet/obs-operator.jsonnet? why?

**Comment by brancz** [comment]
The component is literally just a component, whereas you are configuring concrete use of the component, which is exactly why it should be in the file you linked.

**Comment by clyang82** [comment]
@squat PTAL
Thanks.

**Pull request merged**
