### PR TITLE
Add loglevel config

### PR DESCRIPTION
**Pull request by krasi-georgiev**

### CODE REVIEW

**Comment by brancz** [comment]
Looks like something is up with the operator job. @squat any idea?

**Comment by squat** [comment]
hmm taking a look. We now have debug assets from every PR, so maybe these provide some insight:https://app.circleci.com/pipelines/github/observatorium/deployments/612/workflows/b59ec424-ed00-4cbb-8b5c-69e13a45f268/jobs/2194/artifacts

**Comment by squat** [comment]
I wonder if this is a resources issue flake

**Comment by rollandf** [comment]
From here: https://2194-190750461-gh.circle-artifacts.com/0/tmp/artifacts/default/observatorium-operator-5798f8769b-d92tb-observatorium-operator.logs
```
evel=warn ts=2020-06-24T10:28:48.643355633Z caller=resource.go:167 msg="sync failed" key=observatorium/observatorium-xyz err="failed to render: failed to evaluate: RUNTIME ERROR: Field does not exist: logLevel\n\tcomponents/observatorium.libsonnet:74:40-69\tthunk from <object <anonymous>>\n\tDuring manifestation\t\n"
E0624 10:28:48.643495       1 resource.go:169] Sync "observatorium/observatorium-xyz" failed: failed to render: failed to evaluate: RUNTIME ERROR: Field does not exist: logLevel
	components/observatorium.libsonnet:74:40-69	thunk from <object <anonymous>>
```
You will need to add `logLevel` and `extendedPprof` here:
https://github.com/observatorium/deployments/blob/master/operator/jsonnet/operator-config.libsonnet#L24

**Comment by krasi-georgiev** [comment]
what would be the jsonnet command to trigger this locally so that I can iterate faster on the changes?

**Pull request merged**
