### PR TITLE
Set requests for up test

### PR DESCRIPTION
**Pull request by clyang82**
If a Container specifies its own CPU limit, but does not specify a CPU request, Kubernetes automatically assigns a CPU request that matches the limit. Set requests for up smaller than limit to ensure the tests can be passed in https://github.com/observatorium/operator/pull/52.

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
/assign @squat @brancz 

Please help to review this PR. Thanks.

**Comment by squat** [comment]
This is also true for memory requests/limits, right? Should we explicitly decrease the memory request also?

**Comment by clyang82** [comment]
we have sufficient memory in test cluster. I think we can continue to use `128Mi`.
```
  Resource           Requests      Limits
  --------           --------      ------
  cpu                1500m (75%)   1700m (85%)
  memory             1074Mi (14%)  1774Mi (23%)
```

**Review by kakkoyun — APPROVED** [review]
💯  LGTM

**Comment by squat** [comment]
Ah i see, the problem was that there wasn't enough CPU to schedule during tests

**Pull request merged**
