### PR TITLE
expose fields

### PR DESCRIPTION
**Pull request by clyang82**
expose fields in conf, including `volumeClaimTemplate`, etc. in the past, we allow to configure `storageClassName` in `volumeClaimTemplate`. that is real case in production environment.

partial fix for https://github.com/observatorium/operator/issues/50

/assign @squat @kakkoyun 

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by brancz** [comment]
I think this generally makes sense, but we should enforce that `accessModes: ['ReadWriteOnce']` is always the case, as if this is not the case then there can be various weird situations that the storage was not designed for.

**Comment by clyang82** [comment]
@brancz Thanks for your comment. Do you mean that we should enforce `accessModes: ['ReadWriteOnce']` in operator side?

**Comment by clyang82** [comment]
Agree with your point. I can have another PR in kube-thanos side to enforce it. But I think this PR does not depend on that PR. Can we merge this one firstly? Thanks.

**Comment by brancz** [comment]
Yep, makes sense!

**Review by brancz — APPROVED** [review]

**Comment by clyang82** [comment]
Thanks @brancz

**Pull request merged**
